const PERMISSIONS = {
  ADMIN_ACCESS: 'admin.access',
  USERS_READ: 'users.read',
  USERS_UPDATE: 'users.update',
  SUBSCRIPTIONS_READ: 'subscriptions.read',
  SUBSCRIPTIONS_UPDATE: 'subscriptions.update',
  PAYMENTS_READ: 'payments.read',
  USAGE_READ: 'usage.read',
  PLANS_READ: 'plans.read',
  INTERVIEWS_CREATE: 'interviews.create',
  INTERVIEWS_READ: 'interviews.read',
  RESUMES_CREATE: 'resumes.create',
  PROFILE_READ: 'profile.read',
  PROFILE_UPDATE: 'profile.update',
  SUPPORT_READ: 'support.read',
  SUPPORT_UPDATE: 'support.update',
};

const ROLE_PERMISSIONS = {
  super_admin: ['*'],
  admin: [
    PERMISSIONS.ADMIN_ACCESS,
    PERMISSIONS.USERS_READ,
    PERMISSIONS.USERS_UPDATE,
    PERMISSIONS.SUBSCRIPTIONS_READ,
    PERMISSIONS.SUBSCRIPTIONS_UPDATE,
    PERMISSIONS.PAYMENTS_READ,
    PERMISSIONS.USAGE_READ,
    PERMISSIONS.PLANS_READ,
    PERMISSIONS.SUPPORT_READ,
    PERMISSIONS.SUPPORT_UPDATE,
  ],
  support: [
    PERMISSIONS.ADMIN_ACCESS,
    PERMISSIONS.USERS_READ,
    PERMISSIONS.SUBSCRIPTIONS_READ,
    PERMISSIONS.USAGE_READ,
    PERMISSIONS.SUPPORT_READ,
    PERMISSIONS.SUPPORT_UPDATE,
  ],
  billing_admin: [
    PERMISSIONS.ADMIN_ACCESS,
    PERMISSIONS.SUBSCRIPTIONS_READ,
    PERMISSIONS.SUBSCRIPTIONS_UPDATE,
    PERMISSIONS.PAYMENTS_READ,
  ],
  user: [
    PERMISSIONS.PROFILE_READ,
    PERMISSIONS.PROFILE_UPDATE,
    PERMISSIONS.INTERVIEWS_CREATE,
    PERMISSIONS.INTERVIEWS_READ,
    PERMISSIONS.RESUMES_CREATE,
  ],
};

module.exports = {
  PERMISSIONS,
  ROLE_PERMISSIONS,
};
